### ISSUE TITLE
403 error

### ISSUE THREAD

**Issue by tcroiset** [librato/python-librato#118] opened 2016-06-01 08:59 UTC
Hi,
Some of my calls to submit metrics fail
It concerns calls with many (~200) metrics sent.
It looks like the api returns 403 error (why?), and the parsing of the error fails.

bests,

> Traceback (most recent call last):
> File "/home/vmagent/app/api/views/other.py", line 248, in post
q.submit()
> File "/usr/local/lib/python2.7/dist-packages/librato/queue.py", line 93, in submit
self.connection._mexe("metrics", method="POST", query_props=c)
> File "/usr/local/lib/python2.7/dist-packages/librato/__init__.py", line 180, in _mexe
resp_data, success, backoff = self._process_response(resp, backoff)
> File "/usr/local/lib/python2.7/dist-packages/librato/__init__.py", line 160, in _process_response
raise exceptions.get(resp.status, resp_data)
> File "/usr/local/lib/python2.7/dist-packages/librato/exceptions.py", line 137, in get
return CODES[code](resp_data)
> File "/usr/local/lib/python2.7/dist-packages/librato/exceptions.py", line 119, in __init__
ClientError.__init__(self, 403, msg)
> File "/usr/local/lib/python2.7/dist-packages/librato/exceptions.py", line 32, in __init__
Exception.__init__(self, self.error_message())
File "/usr/local/lib/python2.7/dist-packages/librato/exceptions.py", line 35, in error_message
return "[%s] %s" % (self.code, self._parse_error_message())
File "/usr/local/lib/python2.7/dist-packages/librato/exceptions.py", line 71, in _parse_error_message
payload = self.error_payload['errors']
KeyError: 'errors'

**Comment by drio** [comment] 2016-06-02 13:46
Hi @tcroiset, 

It seems we are receiving an unexpected error payload. Could you please try your code using [this](https://github.com/librato/python-librato/tree/chore/report_error_payload) branch? It should report the error payload so we can identify what the problem is with the request. 

Alternatively, I can try that on my end if you send me the code you are using.

**Comment by jderrett** [comment] 2016-06-30 17:56
Should be fixed in #122

**Closed** 2016-07-05 14:08 UTC
